Add requirements around certificate validity in the absence of Authen…
notaryproject/specifications pull request #178
Opened 2022-07-28 23:26 UTC by rgnote

Clarify requirements around certificate validity if AuthenticTimestamp is not available.

@gokarnm @SteveLasker

Signed-off-by: rgnote <5878554+rgnote@users.noreply.github.com>

2022-07-29 01:34 UTC, SteveLasker commented
adding @shizhMSFT

2022-07-29 02:59 UTC, shizhMSFT commented on trust-store-trust-policy-specification.md
> +**Authentic timestamp** : Guarantees that the signature was generated when the certificate was valid. It also allows a verifier to determine if a signature must be treated as valid or not based on wh
To reduce ambiguity in English.
```suggestion
**Authentic timestamp** : Guarantees that the signature was generated when the certificate was valid. It also allows a verifier to determine if a signature must be treated as valid or invalid based on whether the signature was generated before or after the certificate revocation. In the absence of an Authentic Timestamp, a signature is considered invalid if the signing certificate or chain is either expired or revoked.
```

2022-08-01 19:03 UTC, gokarnm requested changes

2022-08-01 19:03 UTC, gokarnm commented on signature-specification.md
> +1. In the absense of an Authentic Timestamp, each and every certificate in the signature i.e. signing certificate, intermediate certificates, and the root certificate must be valid i.e. not expired a
```suggestion
1. In the absence of an Authentic Timestamp, each and every certificate in the certificate chain i.e. signing certificate, intermediate certificates, and the root certificate must be valid i.e. not expired at the time of signature verification.
```

2022-08-01 19:26 UTC, gokarnm approved these changes
LGTM!

2022-08-02 00:23 UTC, shizhMSFT approved these changes
LGTM

2022-08-03 23:32 UTC, gokarnm commented
@roywill would appreciate your review for this PR.

2022-08-09 00:07 UTC, roywill approved these changes

2022-08-10 17:39 UTC, merged